name: Blog Backend CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    uses: seul394/cicd/.github/workflows/build.yaml@main
    with:
      project: backend
      ecr_repository: blog-backend-${{ github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ needs.build.outputs.image_tag }}"

  deploy: 
    needs: build
    uses: seul394/cicd/.github/workflows/deploy.yaml@main
    with:
      project: backend
      ecr_repository: blog-backend-${{ github.ref_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
